version: "3.8"
services:
  redis:
    image: redis:7
    ports: ["6379:6379"]

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports: ["5432:5432"]

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: productdb
    ports: ["3306:3306"]

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      ACCEPT_EULA: "Y"
    ports: ["1433:1433"]

  eureka:
    build: ./eureka
    ports: ["8761:8761"]
    depends_on: [postgres, mysql]

  gateway:
    build: ./gateway
    ports: ["8080:8080"]
    depends_on: [eureka]

  auth-service:
    build: ./auth-service
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    depends_on: [postgres, eureka]

  product-service:
    build: ./product-service
    depends_on: [mysql, eureka]

  order-service:
    build: ./order-service
    depends_on: [postgres, eureka]

  cart-service:
    build: ./cart-service
    depends_on: [redis, eureka]

  payment-service:
    build: ./payment-service
    depends_on: [mssql, eureka]

  frontend:
    build: ./frontend
    ports: ["4200:80"]
    depends_on: [gateway]

networks:
  default:
    driver: bridge
