version: "3.8"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  auth-service:
    build: .
    ports:
      - "8081:8081"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: authdb
      DB_USER: auth_user
      DB_PASSWORD: auth_pass
      JWT_SECRET: "replace_with_a_long_random_secret_at_least_32_chars"
      JWT_EXPIRATION_MS: 3600000
    depends_on:
      - postgres

volumes:
  pgdata:
