server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/productdb?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: example
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
